@extends('errors.layout')
@section('title', 'Not Found')
@section('code', '404')
@section('message', 'Page Not Found')
@section('description', 'The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.')
